# Configuration for gRPC-based application

[servers]
  [servers.0]
  ip = "10.90.38.14"
  port = 50050

  [servers.1]
  ip = "10.90.39.3"
  port = 50051

  #[servers.2]
  #ip = "0.0.0.0"
  #port = 50052

