# Configuration for gRPC-based application

client = "10.90.40.3"

[servers]
  [servers.0]
  ip = "10.90.39.17"
  port = 50050

  [servers.1]
  ip = "10.90.39.23"
  port = 50051

  #[servers.2]
  #ip = "0.0.0.0"
  #port = 50052

