# Configuration for gRPC-based application

client = "iccluster105.iccluster.epfl.ch"

[servers]
  [servers.0]
ip = "10.90.36.36"
  port = 50050

  [servers.1]
  ip = "10.90.36.37"
  port = 50051

  #[servers.2]
  #ip = "0.0.0.0"
  #port = 50052

