# Configuration for gRPC-based application
[servers]
  [servers.0]
  ip = "iccluster106.iccluster.epfl.ch"
  port = 50050

  [servers.1]
  ip = "iccluster107.iccluster.epfl.ch"
  port = 50051

  #[servers.2]
  #ip = "0.0.0.0"
  #port = 50052

