Name = "fss"
Primitive = "fss"
NumRows = 1
BlockLength = 2
ElementBitSize = 31
#InputSizes = [2, 4, 8, 16, 32, 64]
#InputSizes = [1, 2, 4, 8, 16, 32]
InputSizes = [1, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64]

