Name = "vpirMultiVector"
Primitive = "vpir"
DBLengthsBits = [100.0 1000.0 10000.0 100000.0 1000000.0]
NumRows = 0 # every NumRows != 0 indicate matrix
BlockLength = 16
ElementBitSize = 128
Repetitions = 3
