Name = "vpirSingleVectorKB"
Primitive = "vpir"
# those are indicated in Mbits now
# TODO: fix constant to avoid confusion
DBLengthsBits = [0.01, 0.1, 1.0, 10.0, 100.0]
NumRows = 0 # every NumRows != 0 indicate matrix
BlockLength = 0
ElementBitSize = 1
Repetitions = 3
